### PR TITLE
Network policy struct

### PR DESCRIPTION
**Pull request by john-a-joyce**
Thank you for contributing to this repo. Please use the following template to describe this Pull Request.

**Summary of Problems addressed**

This doesn't address a specific problem in the current content but it is intended to be an initial commit for a complete description of network policy application in a multicloud environment.  

*Found In:* *path/to/file* (if eligible)

Not applicable

**List of relevant Issues being fixed**

An issue has not been created to cover the addition of this new content 

**Summary of Proposed Solution**

The plan here is to use this repository to document how to apply network policy in a multicloud environment and describe the behavior that can be expected.  This is just the first of what is planned to be a number of commits over the next week or so.

### CODE REVIEW

**Comment by subodh-dharma** [comment]
@john-a-joyce I believe this is WIP. Can you rename this folder to `Multicloud Network Policy`. That would give more context from the root of the repo.

**Comment by john-a-joyce** [comment]
Sure I can rename the directory but I don't consider this WIP.  We have most of the content in a PP deck already with two people working on it.  This commit was an attempt to break things up into easily reviewable PRs.  With this PR we are more or less just making sure there are no concerns about the goal, the proposed content and its location.   If the repo needs to stay in a quasi-finished state due to the public being able to access it then I understand the WIP comment and we can bring most of the content in via very large PRs.   If quasi-finished is not a requirement of the repo I would like to understand why this can't merge as is (after the name change).   There is very little to review here.

**Comment by subodh-dharma** [comment]
If the content is ready for publishing and making it public, we are good to go. I wanted to make sure that nothing goes public before any announcements are made.

**Comment by subodh-dharma** [comment]
Merged the PR. The new folder is now in the master branch.

**Pull request merged**
